name: smart_health_assistant
description: A smart health assistant app with step tracking, hydration reminders, and mindfulness nudges.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase Core and Auth
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  # cloud_firestore: ^5.6.6

  # Local Storage
  # shared_preferences: ^2.2.2

  # Step Tracking
  # pedometer: ^4.0.1

  # Notifications
  # firebase_messaging: ^15.2.5
  # flutter_local_notifications: ^19.1.0

  # HTTP for OpenWeatherMap API
  # http: ^1.2.1

  # Platform channel integration
  # flutter_platform_widgets: ^7.0.1

  # Permissions
  # permission_handler: ^11.3.0

  # JSON serialization (optional but useful)
  # json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/